const props = {
  col: "column",
  float: "float",
  clear: "clear",
  family: "family",
  inset: "inset",
  "fx-grow": "flexGrow",
  "fx-shrink": "flexShrink",
  "fx-basis": "flexBasis",
  "place-c": "placeContent",
  "place-i": "placeItems",
  "place-s": "placeSelf",
  "font-s": "fontStyle",
  "font-v-num": "fontVariantNumeric",

  "web-bx-o": "-webkit-box-orient",
  "web-li-c": "-webkit-line-clamp",

  "li-s-img": "listStyleImage",
  "li-s-loc": "listStylePosition",
  "li-s-type": "listStyleType",

  "td-li": "textDecorationLine",
  "td-c": "textDecorationColor",
  "td-s": "textDecorationStyle",
  "td-t": "textDecorationThickness",
  "td-o": "textDecorationOffset",

  "p-il-start": "paddingInlineStart",
  "p-il-end": "paddingInlineStart",
  "m-il-start": "marginInlineStart",
  "m-il-end": "marginInlineStart",
  "inset-il-start": "insetInlineStart",
  "inset-il-end": "insetInlineEnd",
  "br-a": "breakAfter",
  "br-b": "breakBefore",
  "br-in": "breakInside",
  "box-dec-br": "boxDecorationBreak",
  "box-s": "boxSizing",
  "obj-fit": "objectFit",
  "obj-loc": "objectPosition",

  "text-over": "textOverflow",
  "text-wrap": "textWrap",
  "v-align": "verticalAlign",
  "w-brk": "wordBreak",
  "over-wrap": "overflowWrap",
  hyph: "hyphens",
  content: "content",

  "bdr-ss-radius": "border-start-start-radius",
  "bdr-se-radius": "border-start-end-radius",
  "bdr-es-radius": "border-end-start-radius",
  "bdr-ee-radius": "border-end-end-radius",
  "bdr-is-width": "border-inline-start-width",
  "bdr-ie-width": "border-inline-end-width",

  "os-b": "overscrollBehavior",
  "os-b-x": "overscrollBehaviorX",
  "os-b-y": "overscrollBehaviorY",

  "web-fs": "-webkit-font-smoothing",
  "moz-fs": "-moz-osx-font-smoothing",
};
