/*!
 * tailwind styles (https://github.com/nousantx/tailwind-classname)
 * Copyright (c) 2024 NOuSantx
 * Licensed under the MIT License (https://github.com/tenoxui/css/blob/main/LICENSE)
 *
 * Tailwind CSS (https://tailwindcss.com/)
 * Copyright (c) 2024 Tailwind Labs Inc.
 * Licensed under the MIT License (https://github.com/tailwindlabs/tailwindcss/blob/next/LICENSE)
 */

const tailwindClass = {
  // aspect ratio
  ".aspect-auto": "ratio-auto",
  ".aspect-square": "ratio-[tx__square]",
  ".aspect-video": "ratio-[tx__video]",
  // Container
  "": "",
  // columns
  ".columns-1": "col-1",
  ".columns-2": "col-2",
  ".columns-3": "col-3",
  ".columns-4": "col-4",
  ".columns-5": "col-5",
  ".columns-6": "col-6",
  ".columns-7": "col-7",
  ".columns-8": "col-8",
  ".columns-9": "col-9",
  ".columns-10": "col-10",
  ".columns-11": "col-11",
  ".columns-12": "col-12",
  ".columns-auto": "col-auto",
  ".columns-3xs": "col-16rem",
  ".columns-2xs": "col-18rem",
  ".columns-xs": "col-20rem",
  ".columns-sm": "col-24rem",
  ".columns-md": "col-28rem",
  ".columns-lg": "col-32rem",
  ".columns-xl": "col-36rem",
  ".columns-2xl": "col-42rem",
  ".columns-3xl": "col-48rem",
  ".columns-4xl": "col-56rem",
  ".columns-5xl": "col-64rem",
  ".columns-6xl": "col-72rem",
  ".columns-7xl": "col-80rem",
  // break after
  ".break-after-auto": "br-a-auto",
  ".break-after-avoid": "br-a-avoid",
  ".break-after-all": "br-a-all",
  ".break-after-avoid-page": "br-a-[tx__avoid-page]",
  ".break-after-page": "br-a-page",
  ".break-after-left": "br-a-left",
  ".break-after-right": "br-a-right",
  ".break-after-column": "br-a-column",
  // break before
  ".break-before-auto": "br-b-auto",
  ".break-before-avoid": "br-b-avoid",
  ".break-before-all": "br-b-all",
  ".break-before-avoid-page": "br-b-[tx__avoid-page]",
  ".break-before-page": "br-b-page",
  ".break-before-left": "br-b-left",
  ".break-before-right": "br-b-right",
  ".break-before-column": "br-b-column",
  // break inside
  ".break-inside-auto": "br-in-auto",
  ".break-inside-avoid": "br-in-avoid",
  ".break-inside-avoid-page": "br-in-[tx__avoid-page]",
  ".break-inside-avoid-column": "br-in-[tx__avoid-column]",
  // box decoration break
  ".box-decoration-clone": "box-dec-br-clone",
  ".box-decoration-slice": "box-dec-br-slice",
  // box sizing
  ".box-border": "box-s-[tx__border-box]",
  ".box-content": "box-s-[tx__content-box]",
  // display
  ".block": "d-block",
  ".inline-block": "d-[tx__inline-block]",
  ".inline": "d-inline",
  ".flex": "d-flex",
  ".inline-flex": "d-[tx__inline-flex]",
  ".table": "d-table",
  ".inline-table": "d-[tx__inline-table]",
  ".table-caption": "d-[tx__table-caption]",
  ".table-cell": "d-[tx__table-cell]",
  ".table-column": "d-[tx__table-column]",
  ".table-column-group": "d-[tx__table-column-group]",
  ".table-footer-group": "d-[tx__table-footer-group]",
  ".table-header-group": "d-[tx__table-header-group]",
  ".table-row-group": "d-[tx__table-row-group]",
  ".table-row": "d-[tx__table-row]",
  ".flow-root": "d-[tx__flow-root]",
  ".grid": "d-grid",
  ".inline-grid": "d-{inline-grid}",
  ".contents": "d-contents",
  ".list-item": "d-[tx__list-item]",
  ".hidden": "d-none",
  // float
  ".float-start": "fl-[tx__inline-start]",
  ".float-end": "fl-[tx__inline-end]",
  ".float-right": "fl-right",
  ".float-left": "fl-left",
  ".float-none": "fl-none",
  // clear
  ".clear-start": "cl-[tx__inline-start]",
  ".clear-end": "cl-[tx__inline-end]",
  ".clear-left": "cl-left",
  ".clear-right": "cl-right",
  ".clear-both": "cl-both",
  ".clear-none": "cl-none",
  // isolation
  ".isolate": "isolation-isolate",
  ".isolation-auto": "isolation-auto",
  // object fit
  ".object-contain": "obj-fit-contain",
  ".object-cover": "obj-fit-cover",
  ".object-fill": "obj-fit-fill",
  ".object-none": "obj-fit-none",
  ".object-scale-down": "obj-fit-[tx__scale-down]",
  // object position
  ".object-bottom": "obj-loc-bottom",
  ".object-center": "obj-loc-center",
  ".object-left": "obj-loc-left",
  ".object-left-bottom": "obj-loc-[tx__left-bottom]",
  ".object-left-top": "obj-loc-[tx__left-top]",
  ".object-right": "obj-loc-right",
  ".object-right-bottom": "obj-loc-[tx__right-bottom]",
  ".object-right-top": "obj-loc-[tx__right-top]",
  ".object-top": "obj-loc-top",
  // overflow
  ".overflow-auto": "over-auto",
  ".overflow-hidden": "over-hidden",
  ".overflow-clip": "over-clip",
  ".overflow-visible": "over-visible",
  ".overflow-scroll": "over-scroll",
  ".overflow-x-auto": "over-x-auto",
  ".overflow-y-auto": "over-y-auto",
  ".overflow-x-hidden": "over-x-hidden",
  ".overflow-y-hidden": "over-y-hidden",
  ".overflow-x-clip": "over-x-clip",
  ".overflow-y-clip": "over-y-clip",
  ".overflow-x-visible": "over-x-visible",
  ".overflow-y-visible": "over-y-visible",
  ".overflow-x-scroll": "over-x-scroll",
  ".overflow-y-scroll": "over-y-scroll",
  // overscroll behavior
  ".overscroll-auto": "os-b-auto",
  ".overscroll-contain": "os-b-contain",
  ".overscroll-none": "os-b-none",
  ".overscroll-y-auto": "os-b-y-auto",
  ".overscroll-y-contain": "os-b-y-contain",
  ".overscroll-y-none": "os-b-y-none",
  ".overscroll-x-auto": "os-b-x-auto",
  ".overscroll-x-contain": "os-b-x-contain",
  ".overscroll-x-none": "os-b-x-none",
  // position
  ".static": "position-static",
  ".fixed": "position-fixed",
  ".absolute": "position-absolute",
  ".relative": "position-relative",
  ".sticky": "position-sticky",
  // top left bottom right
  // visibility
  ".visible": "visibility-visible",
  ".invisible": "visibility-hidden",
  ".collapse": "visibility-collapse",
  // z-index
  ".z-0": "z-0",
  ".z-10": "z-10",
  ".z-20": "z-20",
  ".z-30": "z-30",
  ".z-40": "z-40",
  ".z-50": "z-50",
  ".z-auto": "z-auto",
  // flex basis
  ".basis-0": "fx-basis-0px",
  ".basis-1": "fx-basis-0.25rem",
  ".basis-2": "fx-basis-0.5rem",
  ".basis-3": "fx-basis-0.75rem",
  ".basis-4": "fx-basis-1rem",
  ".basis-5": "fx-basis-1.25rem",
  ".basis-6": "fx-basis-1.5rem",
  ".basis-7": "fx-basis-1.75rem",
  ".basis-8": "fx-basis-2rem",
  ".basis-9": "fx-basis-2.25rem",
  ".basis-10": "fx-basis-2.5rem",
  ".basis-11": "fx-basis-2.75rem",
  ".basis-12": "fx-basis-3rem",
  ".basis-14": "fx-basis-3.5rem",
  ".basis-16": "fx-basis-4rem",
  ".basis-20": "fx-basis-5rem",
  ".basis-24": "fx-basis-6rem",
  ".basis-28": "fx-basis-7rem",
  ".basis-32": "fx-basis-8rem",
  ".basis-36": "fx-basis-9rem",
  ".basis-40": "fx-basis-10rem",
  ".basis-44": "fx-basis-11rem",
  ".basis-48": "fx-basis-12rem",
  ".basis-52": "fx-basis-13rem",
  ".basis-56": "fx-basis-14rem",
  ".basis-60": "fx-basis-15rem",
  ".basis-64": "fx-basis-16rem",
  ".basis-72": "fx-basis-18rem",
  ".basis-80": "fx-basis-20rem",
  ".basis-96": "fx-basis-24rem",
  ".basis-auto": "fx-basis-auto",
  ".basis-px": "fx-basis-1px",
  ".basis-0.5": "fx-basis-0.125rem",
  ".basis-1.5": "fx-basis-0.375rem",
  ".basis-2.5": "fx-basis-0.625rem",
  ".basis-3.5": "fx-basis-0.875rem",
  ".basis-1/2": "fx-basis-50%",
  ".basis-1/3": "fx-basis-33.333333%",
  ".basis-2/3": "fx-basis-66.666667%",
  ".basis-1/4": "fx-basis-25%",
  ".basis-2/4": "fx-basis-50%",
  ".basis-3/4": "fx-basis-75%",
  ".basis-1/5": "fx-basis-20%",
  ".basis-2/5": "fx-basis-40%",
  ".basis-3/5": "fx-basis-60%",
  ".basis-4/5": "fx-basis-80%",
  ".basis-1/6": "fx-basis-16.666667%",
  ".basis-2/6": "fx-basis-33.333333%",
  ".basis-3/6": "fx-basis-50%",
  ".basis-4/6": "fx-basis-66.666667%",
  ".basis-5/6": "fx-basis-83.333333%",
  ".basis-1/12": "fx-basis-8.333333%",
  ".basis-2/12": "fx-basis-16.666667%",
  ".basis-3/12": "fx-basis-25%",
  ".basis-4/12": "fx-basis-33.333333%",
  ".basis-5/12": "fx-basis-41.666667%",
  ".basis-6/12": "fx-basis-50%",
  ".basis-7/12": "fx-basis-58.333333%",
  ".basis-8/12": "fx-basis-66.666667%",
  ".basis-9/12": "fx-basis-75%",
  ".basis-10/12": "fx-basis-83.333333%",
  ".basis-11/12": "fx-basis-91.666667%",
  ".basis-full": "fx-basis-100%",
  // flex direction
  ".flex-row": "fd-row",
  ".flex-row-reverse": "fd-[tx__row-reverse]",
  ".flex-col": "fd-column",
  ".flex-col-reverse": "fd-[tx__column-reverse]",
  // flex wrap
  ".flex-wrap": "fx-wrap-wrap",
  ".flex-wrap-reverse": "fx-wrap-[tx__wrap-reverse]",
  ".flex-nowrap": "fx-wrap-nowrap",
  // flex
  ".flex-1": "fx-grow-1 fx-shrink-1 fx-basis-0%",
  ".flex-auto": "fx-grow-1 fx-shrink-1 fx-basis-auto",
  ".flex-initial": "fx-grow-0 fx-shrink-1 fx-basis-auto",
  ".flex-none": "flex-none",
  // flex grow
  ".grow": "fx-grow-1",
  ".grow-0": "fx-grow-0",
  // flex shrink
  ".shrink": "fx-shrink-1",
  ".shrink-0": "fx-shrink-0",
  // order
  ".order-1": "order-1",
  ".order-2": "order-2",
  ".order-3": "order-3",
  ".order-4": "order-4",
  ".order-5": "order-5",
  ".order-6": "order-6",
  ".order-7": "order-7",
  ".order-8": "order-8",
  ".order-9": "order-9",
  ".order-10": "order-10",
  ".order-11": "order-11",
  ".order-12": "order-12",
  ".order-first": "order--9999",
  ".order-last": "order-9999",
  ".order-none": "order-0",
  // gap
  ".gap-0": "gap-0px",
  ".gap-x-0": "gap-x-0px",
  ".gap-y-0": "gap-y-0px",
  ".gap-px": "gap-1px",
  ".gap-x-px": "gap-x-1px",
  ".gap-y-px": "gap-y-1px",
  ".gap-0.5": "gap-0.125rem",
  ".gap-x-0.5": "gap-x-0.125rem",
  ".gap-y-0.5": "gap-y-0.125rem",
  ".gap-1": "gap-0.25rem",
  ".gap-x-1": "gap-x-0.25rem",
  ".gap-y-1": "gap-y-0.25rem",
  ".gap-1.5": "gap-0.375rem",
  ".gap-x-1.5": "gap-x-0.375rem",
  ".gap-y-1.5": "gap-y-0.375rem",
  ".gap-2": "gap-0.5rem",
  ".gap-x-2": "gap-x-0.5rem",
  ".gap-y-2": "gap-y-0.5rem",
  ".gap-2.5": "gap-0.625rem",
  ".gap-x-2.5": "gap-x-0.625rem",
  ".gap-y-2.5": "gap-y-0.625rem",
  ".gap-3": "gap-0.75rem",
  ".gap-x-3": "gap-x-0.75rem",
  ".gap-y-3": "gap-y-0.75rem",
  ".gap-3.5": "gap-0.875rem",
  ".gap-x-3.5": "gap-x-0.875rem",
  ".gap-y-3.5": "gap-y-0.875rem",
  ".gap-4": "gap-1rem",
  ".gap-x-4": "gap-x-1rem",
  ".gap-y-4": "gap-y-1rem",
  ".gap-5": "gap-1.25rem",
  ".gap-x-5": "gap-x-1.25rem",
  ".gap-y-5": "gap-y-1.25rem",
  ".gap-6": "gap-1.5rem",
  ".gap-x-6": "gap-x-1.5rem",
  ".gap-y-6": "gap-y-1.5rem",
  ".gap-7": "gap-1.75rem",
  ".gap-x-7": "gap-x-1.75rem",
  ".gap-y-7": "gap-y-1.75rem",
  ".gap-8": "gap-2rem",
  ".gap-x-8": "gap-x-2rem",
  ".gap-y-8": "gap-y-2rem",
  ".gap-9": "gap-2.25rem",
  ".gap-x-9": "gap-x-2.25rem",
  ".gap-y-9": "gap-y-2.25rem",
  ".gap-10": "gap-2.5rem",
  ".gap-x-10": "gap-x-2.5rem",
  ".gap-y-10": "gap-y-2.5rem",
  ".gap-11": "gap-2.75rem",
  ".gap-x-11": "gap-x-2.75rem",
  ".gap-y-11": "gap-y-2.75rem",
  ".gap-12": "gap-3rem",
  ".gap-x-12": "gap-x-3rem",
  ".gap-y-12": "gap-y-3rem",
  ".gap-14": "gap-3.5rem",
  ".gap-x-14": "gap-x-3.5rem",
  ".gap-y-14": "gap-y-3.5rem",
  ".gap-16": "gap-4rem",
  ".gap-x-16": "gap-x-4rem",
  ".gap-y-16": "gap-y-4rem",
  ".gap-20": "gap-5rem",
  ".gap-x-20": "gap-x-5rem",
  ".gap-y-20": "gap-y-5rem",
  ".gap-24": "gap-6rem",
  ".gap-x-24": "gap-x-6rem",
  ".gap-y-24": "gap-y-6rem",
  ".gap-28": "gap-7rem",
  ".gap-x-28": "gap-x-7rem",
  ".gap-y-28": "gap-y-7rem",
  ".gap-32": "gap-8rem",
  ".gap-x-32": "gap-x-8rem",
  ".gap-y-32": "gap-y-8rem",
  ".gap-36": "gap-9rem",
  ".gap-x-36": "gap-x-9rem",
  ".gap-y-36": "gap-y-9rem",
  ".gap-40": "gap-10rem",
  ".gap-x-40": "gap-x-10rem",
  ".gap-y-40": "gap-y-10rem",
  ".gap-44": "gap-11rem",
  ".gap-x-44": "gap-x-11rem",
  ".gap-y-44": "gap-y-11rem",
  ".gap-48": "gap-12rem",
  ".gap-x-48": "gap-x-12rem",
  ".gap-y-48": "gap-y-12rem",
  ".gap-52": "gap-13rem",
  ".gap-x-52": "gap-x-13rem",
  ".gap-y-52": "gap-y-13rem",
  ".gap-56": "gap-14rem",
  ".gap-x-56": "gap-x-14rem",
  ".gap-y-56": "gap-y-14rem",
  ".gap-60": "gap-15rem",
  ".gap-x-60": "gap-x-15rem",
  ".gap-y-60": "gap-y-15rem",
  ".gap-64": "gap-16rem",
  ".gap-x-64": "gap-x-16rem",
  ".gap-y-64": "gap-y-16rem",
  ".gap-72": "gap-18rem",
  ".gap-x-72": "gap-x-18rem",
  ".gap-y-72": "gap-y-18rem",
  ".gap-80": "gap-20rem",
  ".gap-x-80": "gap-x-20rem",
  ".gap-y-80": "gap-y-20rem",
  ".gap-96": "gap-24rem",
  ".gap-x-96": "gap-x-24rem",
  ".gap-y-96": "gap-y-24rem",
  // justify content
  ".justify-normal": "jc-normal",
  ".justify-start": "jc-[tx__flex-start]",
  ".justify-end": "jc-[tx__flex-end]",
  ".justify-center": "jc-center",
  ".justify-between": "jc-[tx__space-between]",
  ".justify-around": "jc-[tx__space-around]",
  ".justify-evenly": "jc-[tx__space-evenly]",
  ".justify-stretch": "jc-stretch",
  // justify items
  ".justify-items-start": "ji-start",
  ".justify-items-end": "ji-end",
  ".justify-items-center": "ji-center",
  ".justify-items-stretch": "ji-stretch",
  // justify self
  ".justify-self-auto": "js-auto",
  ".justify-self-start": "js-start",
  ".justify-self-end": "js-end",
  ".justify-self-center": "js-center",
  ".justify-self-stretch": "js-stretch",
  // align content
  ".content-normal": "ac-normal",
  ".content-center": "ac-center",
  ".content-start": "ac-[tx__flex-start]",
  ".content-end": "ac-[tx__flex-end]",
  ".content-between": "ac-[tx__space-between]",
  ".content-around": "ac-[tx__space-around]",
  ".content-evenly": "ac-[tx__space-evenly]",
  ".content-baseline": "ac-baseline",
  ".content-stretch": "ac-stretch",
  // align items
  ".items-start": "ai-[tx__flex-start]",
  ".items-end": "ai-[tx__flex-end]",
  ".items-center": "ai-center",
  ".items-baseline": "ai-baseline",
  ".items-stretch": "ai-stretch",
  // align self
  ".self-auto": "as-auto",
  ".self-start": "as-[tx__flex-start]",
  ".self-end": "as-[tx__flex-end]",
  ".self-center": "as-center",
  ".self-stretch": "as-stretch",
  ".self-baseline": "as-baseline",
  // place content
  ".place-content-center": "place-c-center",
  ".place-content-start": "place-c-start",
  ".place-content-end": "place-c-end",
  ".place-content-between": "place-c-[tx__space-between]",
  ".place-content-around": "place-c-[tx__space-around]",
  ".place-content-evenly": "place-c-[tx__space-evenly]",
  ".place-content-baseline": "place-c-baseline",
  ".place-content-stretch": "place-c-stretch",
  // place items
  ".place-items-start": "place-i-start",
  ".place-items-end": "place-i-end",
  ".place-items-center": "place-i-center",
  ".place-items-baseline": "place-i-baseline",
  ".place-items-stretch": "place-i-stretch",
  // place self
  ".place-self-auto": "place-s-auto",
  ".place-self-start": "place-s-start",
  ".place-self-end": "place-s-end",
  ".place-self-center": "place-s-center",
  ".place-self-stretch": "place-s-stretch",
  // space between
  ".space-x-0 > * + *": "ml-0px",
  ".space-y-0 > * + *": "mt-0px",
  ".space-x-0.5 > * + *": "ml-0.125rem",
  ".space-y-0.5 > * + *": "mt-0.125rem",
  ".space-x-1 > * + *": "ml-0.25rem",
  ".space-y-1 > * + *": "mt-0.25rem",
  ".space-x-1.5 > * + *": "ml-0.375rem",
  ".space-y-1.5 > * + *": "mt-0.375rem",
  ".space-x-2 > * + *": "ml-0.5rem",
  ".space-y-2 > * + *": "mt-0.5rem",
  ".space-x-2.5 > * + *": "ml-0.625rem",
  ".space-y-2.5 > * + *": "mt-0.625rem",
  ".space-x-3 > * + *": "ml-0.75rem",
  ".space-y-3 > * + *": "mt-0.75rem",
  ".space-x-3.5 > * + *": "ml-0.875rem",
  ".space-y-3.5 > * + *": "mt-0.875rem",
  ".space-x-4 > * + *": "ml-1rem",
  ".space-y-4 > * + *": "mt-1rem",
  ".space-x-5 > * + *": "ml-1.25rem",
  ".space-y-5 > * + *": "mt-1.25rem",
  ".space-x-6 > * + *": "ml-1.5rem",
  ".space-y-6 > * + *": "mt-1.5rem",
  ".space-x-7 > * + *": "ml-1.75rem",
  ".space-y-7 > * + *": "mt-1.75rem",
  ".space-x-8 > * + *": "ml-2rem",
  ".space-y-8 > * + *": "mt-2rem",
  ".space-x-9 > * + *": "ml-2.25rem",
  ".space-y-9 > * + *": "mt-2.25rem",
  ".space-x-10 > * + *": "ml-2.5rem",
  ".space-y-10 > * + *": "mt-2.5rem",
  ".space-x-11 > * + *": "ml-2.75rem",
  ".space-y-11 > * + *": "mt-2.75rem",
  ".space-x-12 > * + *": "ml-3rem",
  ".space-y-12 > * + *": "mt-3rem",
  ".space-x-14 > * + *": "ml-3.5rem",
  ".space-y-14 > * + *": "mt-3.5rem",
  ".space-x-16 > * + *": "ml-4rem",
  ".space-y-16 > * + *": "mt-4rem",
  ".space-x-20 > * + *": "ml-5rem",
  ".space-y-20 > * + *": "mt-5rem",
  ".space-x-24 > * + *": "ml-6rem",
  ".space-y-24 > * + *": "mt-6rem",
  ".space-x-28 > * + *": "ml-7rem",
  ".space-y-28 > * + *": "mt-7rem",
  ".space-x-32 > * + *": "ml-8rem",
  ".space-y-32 > * + *": "mt-8rem",
  ".space-x-36 > * + *": "ml-9rem",
  ".space-y-36 > * + *": "mt-9rem",
  ".space-x-40 > * + *": "ml-10rem",
  ".space-y-40 > * + *": "mt-10rem",
  ".space-x-44 > * + *": "ml-11rem",
  ".space-y-44 > * + *": "mt-11rem",
  ".space-x-48 > * + *": "ml-12rem",
  ".space-y-48 > * + *": "mt-12rem",
  ".space-x-52 > * + *": "ml-13rem",
  ".space-y-52 > * + *": "mt-13rem",
  ".space-x-56 > * + *": "ml-14rem",
  ".space-y-56 > * + *": "mt-14rem",
  ".space-x-60 > * + *": "ml-15rem",
  ".space-y-60 > * + *": "mt-15rem",
  ".space-x-64 > * + *": "ml-16rem",
  ".space-y-64 > * + *": "mt-16rem",
  ".space-x-72 > * + *": "ml-18rem",
  ".space-y-72 > * + *": "mt-18rem",
  ".space-x-80 > * + *": "ml-20rem",
  ".space-y-80 > * + *": "mt-20rem",
  ".space-x-96 > * + *": "ml-24rem",
  ".space-y-96 > * + *": "mt-24rem",
  ".space-x-px > * + *": "ml-1px",
  ".space-y-px > * + *": "mt-1px",
  ".-space-x-0 > * + *": "ml--0px",
  ".-space-y-0 > * + *": "mt--0px",
  ".-space-x-0.5 > * + *": "ml--0.125rem",
  ".-space-y-0.5 > * + *": "mt--0.125rem",
  ".-space-x-1 > * + *": "ml--0.25rem",
  ".-space-y-1 > * + *": "mt--0.25rem",
  ".-space-x-1.5 > * + *": "ml--0.375rem",
  ".-space-y-1.5 > * + *": "mt--0.375rem",
  ".-space-x-2 > * + *": "ml--0.5rem",
  ".-space-y-2 > * + *": "mt--0.5rem",
  ".-space-x-2.5 > * + *": "ml--0.625rem",
  ".-space-y-2.5 > * + *": "mt--0.625rem",
  ".-space-x-3 > * + *": "ml--0.75rem",
  ".-space-y-3 > * + *": "mt--0.75rem",
  ".-space-x-3.5 > * + *": "ml--0.875rem",
  ".-space-y-3.5 > * + *": "mt--0.875rem",
  ".-space-x-4 > * + *": "ml--1rem",
  ".-space-y-4 > * + *": "mt--1rem",
  ".-space-x-5 > * + *": "ml--1.25rem",
  ".-space-y-5 > * + *": "mt--1.25rem",
  ".-space-x-6 > * + *": "ml--1.5rem",
  ".-space-y-6 > * + *": "mt--1.5rem",
  ".-space-x-7 > * + *": "ml--1.75rem",
  ".-space-y-7 > * + *": "mt--1.75rem",
  ".-space-x-8 > * + *": "ml--2rem",
  ".-space-y-8 > * + *": "mt--2rem",
  ".-space-x-9 > * + *": "ml--2.25rem",
  ".-space-y-9 > * + *": "mt--2.25rem",
  ".-space-x-10 > * + *": "ml--2.5rem",
  ".-space-y-10 > * + *": "mt--2.5rem",
  ".-space-x-11 > * + *": "ml--2.75rem",
  ".-space-y-11 > * + *": "mt--2.75rem",
  ".-space-x-12 > * + *": "ml--3rem",
  ".-space-y-12 > * + *": "mt--3rem",
  ".-space-x-14 > * + *": "ml--3.5rem",
  ".-space-y-14 > * + *": "mt--3.5rem",
  ".-space-x-16 > * + *": "ml--4rem",
  ".-space-y-16 > * + *": "mt--4rem",
  ".-space-x-20 > * + *": "ml--5rem",
  ".-space-y-20 > * + *": "mt--5rem",
  ".-space-x-24 > * + *": "ml--6rem",
  ".-space-y-24 > * + *": "mt--6rem",
  ".-space-x-28 > * + *": "ml--7rem",
  ".-space-y-28 > * + *": "mt--7rem",
  ".-space-x-32 > * + *": "ml--8rem",
  ".-space-y-32 > * + *": "mt--8rem",
  ".-space-x-36 > * + *": "ml--9rem",
  ".-space-y-36 > * + *": "mt--9rem",
  ".-space-x-40 > * + *": "ml--10rem",
  ".-space-y-40 > * + *": "mt--10rem",
  ".-space-x-44 > * + *": "ml--11rem",
  ".-space-y-44 > * + *": "mt--11rem",
  ".-space-x-48 > * + *": "ml--12rem",
  ".-space-y-48 > * + *": "mt--12rem",
  ".-space-x-52 > * + *": "ml--13rem",
  ".-space-y-52 > * + *": "mt--13rem",
  ".-space-x-56 > * + *": "ml--14rem",
  ".-space-y-56 > * + *": "mt--14rem",
  ".-space-x-60 > * + *": "ml--15rem",
  ".-space-y-60 > * + *": "mt--15rem",
  ".-space-x-64 > * + *": "ml--16rem",
  ".-space-y-64 > * + *": "mt--16rem",
  ".-space-x-72 > * + *": "ml--18rem",
  ".-space-y-72 > * + *": "mt--18rem",
  ".-space-x-80 > * + *": "ml--20rem",
  ".-space-y-80 > * + *": "mt--20rem",
  ".-space-x-96 > * + *": "ml--24rem",
  ".-space-y-96 > * + *": "mt--24rem",
  ".-space-x-px > * + *": "ml--1px",
  ".-space-y-px > * + *": "mt--1px",
  // width
  ".w-0": "w-0px",
  ".w-px": "w-1px",
  ".w-0.5": "w-0.125rem",
  ".w-1": "w-0.25rem",
  ".w-1.5": "w-0.375rem",
  ".w-2": "w-0.5rem",
  ".w-2.5": "w-0.625rem",
  ".w-3": "w-0.75rem",
  ".w-3.5": "w-0.875rem",
  ".w-4": "w-1rem",
  ".w-5": "w-1.25rem",
  ".w-6": "w-1.5rem",
  ".w-7": "w-1.75rem",
  ".w-8": "w-2rem",
  ".w-9": "w-2.25rem",
  ".w-10": "w-2.5rem",
  ".w-11": "w-2.75rem",
  ".w-12": "w-3rem",
  ".w-14": "w-3.5rem",
  ".w-16": "w-4rem",
  ".w-20": "w-5rem",
  ".w-24": "w-6rem",
  ".w-28": "w-7rem",
  ".w-32": "w-8rem",
  ".w-36": "w-9rem",
  ".w-40": "w-10rem",
  ".w-44": "w-11rem",
  ".w-48": "w-12rem",
  ".w-52": "w-13rem",
  ".w-56": "w-14rem",
  ".w-60": "w-15rem",
  ".w-64": "w-16rem",
  ".w-72": "w-18rem",
  ".w-80": "w-20rem",
  ".w-96": "w-24rem",
  ".w-auto": "w-auto",
  ".w-1/2": "w-50%",
  ".w-1/3": "w-33.333333%",
  ".w-2/3": "w-66.666667%",
  ".w-1/4": "w-25%",
  ".w-2/4": "w-50%",
  ".w-3/4": "w-75%",
  ".w-1/5": "w-20%",
  ".w-2/5": "w-40%",
  ".w-3/5": "w-60%",
  ".w-4/5": "w-80%",
  ".w-1/6": "w-16.666667%",
  ".w-2/6": "w-33.333333%",
  ".w-3/6": "w-50%",
  ".w-4/6": "w-66.666667%",
  ".w-5/6": "w-83.333333%",
  ".w-1/12": "w-8.333333%",
  ".w-2/12": "w-16.666667%",
  ".w-3/12": "w-25%",
  ".w-4/12": "w-33.333333%",
  ".w-5/12": "w-41.666667%",
  ".w-6/12": "w-50%",
  ".w-7/12": "w-58.333333%",
  ".w-8/12": "w-66.666667%",
  ".w-9/12": "w-75%",
  ".w-10/12": "w-83.333333%",
  ".w-11/12": "w-91.666667%",
  ".w-full": "w-100%",
  ".w-screen": "w-100vw",
  ".w-svw": "w-100svw",
  ".w-lvw": "w-100lvw",
  ".w-dvw": "w-100dvw",
  ".w-min": "w-[tx__min-content]",
  ".w-max": "w-[tx__max-content]",
  ".w-fit": "w-[tx__fit-content]",
  // min width

  ".min-w-0": "w-mn-0px",
  ".min-w-1": "w-mn-0.25rem",
  ".min-w-2": "w-mn-0.5rem",
  ".min-w-3": "w-mn-0.75rem",
  ".min-w-4": "w-mn-1rem",
  ".min-w-5": "w-mn-1.25rem",
  ".min-w-6": "w-mn-1.5rem",
  ".min-w-7": "w-mn-1.75rem",
  ".min-w-8": "w-mn-2rem",
  ".min-w-9": "w-mn-2.25rem",
  ".min-w-10": "w-mn-2.5rem",
  ".min-w-11": "w-mn-2.75rem",
  ".min-w-12": "w-mn-3rem",
  ".min-w-14": "w-mn-3.5rem",
  ".min-w-16": "w-mn-4rem",
  ".min-w-20": "w-mn-5rem",
  ".min-w-24": "w-mn-6rem",
  ".min-w-28": "w-mn-7rem",
  ".min-w-32": "w-mn-8rem",
  ".min-w-36": "w-mn-9rem",
  ".min-w-40": "w-mn-10rem",
  ".min-w-44": "w-mn-11rem",
  ".min-w-48": "w-mn-12rem",
  ".min-w-52": "w-mn-13rem",
  ".min-w-56": "w-mn-14rem",
  ".min-w-60": "w-mn-15rem",
  ".min-w-64": "w-mn-16rem",
  ".min-w-72": "w-mn-18rem",
  ".min-w-80": "w-mn-20rem",
  ".min-w-96": "w-mn-24rem",
  ".min-w-px": "w-mn-1px",
  ".min-w-0.5": "w-mn-0.125rem",
  ".min-w-1.5": "w-mn-0.375rem",
  ".min-w-2.5": "w-mn-0.625rem",
  ".min-w-3.5": "w-mn-0.875rem",
  ".min-w-full": "w-mn-100%",
  ".min-w-min": "w-mn-[tx__min-content]",
  ".min-w-max": "w-mn-[tx__max-content]",
  ".min-w-fit": "w-mn-[tx__fit-content]",
  // max width

  ".max-w-0": "w-mx-0px",
  ".max-w-px": "w-mx-1px",
  ".max-w-0.5": "w-mx-0.125rem",
  ".max-w-1": "w-mx-0.25rem",
  ".max-w-1.5": "w-mx-0.375rem",
  ".max-w-2": "w-mx-0.5rem",
  ".max-w-2.5": "w-mx-0.625rem",
  ".max-w-3": "w-mx-0.75rem",
  ".max-w-3.5": "w-mx-0.875rem",
  ".max-w-4": "w-mx-1rem",
  ".max-w-5": "w-mx-1.25rem",
  ".max-w-6": "w-mx-1.5rem",
  ".max-w-7": "w-mx-1.75rem",
  ".max-w-8": "w-mx-2rem",
  ".max-w-9": "w-mx-2.25rem",
  ".max-w-10": "w-mx-2.5rem",
  ".max-w-11": "w-mx-2.75rem",
  ".max-w-12": "w-mx-3rem",
  ".max-w-14": "w-mx-3.5rem",
  ".max-w-16": "w-mx-4rem",
  ".max-w-20": "w-mx-5rem",
  ".max-w-24": "w-mx-6rem",
  ".max-w-28": "w-mx-7rem",
  ".max-w-32": "w-mx-8rem",
  ".max-w-36": "w-mx-9rem",
  ".max-w-40": "w-mx-10rem",
  ".max-w-44": "w-mx-11rem",
  ".max-w-48": "w-mx-12rem",
  ".max-w-52": "w-mx-13rem",
  ".max-w-56": "w-mx-14rem",
  ".max-w-60": "w-mx-15rem",
  ".max-w-64": "w-mx-16rem",
  ".max-w-72": "w-mx-18rem",
  ".max-w-80": "w-mx-20rem",
  ".max-w-96": "w-mx-24rem",
  ".max-w-none": "w-mx-none",
  ".max-w-xs": "w-mx-20rem",
  ".max-w-sm": "w-mx-24rem",
  ".max-w-md": "w-mx-28rem",
  ".max-w-lg": "w-mx-32rem",
  ".max-w-xl": "w-mx-36rem",
  ".max-w-2xl": "w-mx-42rem",
  ".max-w-3xl": "w-mx-48rem",
  ".max-w-4xl": "w-mx-56rem",
  ".max-w-5xl": "w-mx-64rem",
  ".max-w-6xl": "w-mx-72rem",
  ".max-w-7xl": "w-mx-80rem",
  ".max-w-full": "w-mx-100%",
  ".max-w-min": "w-mx-[tx__min-content]",
  ".max-w-max": "w-mx-[tx__max-content]",
  ".max-w-fit": "w-mx-[tx__fit-content]",
  ".max-w-prose": "w-mx-65ch",
  ".max-w-screen-sm": "w-mx-640px",
  ".max-w-screen-md": "w-mx-768px",
  ".max-w-screen-lg": "w-mx-1024px",
  ".max-w-screen-xl": "w-mx-1280px",
  ".max-w-screen-2xl": "w-mx-1536px",
  // height

  ".h-0": "h-0px",
  ".h-px": "h-1px",
  ".h-0.5": "h-0.125rem",
  ".h-1": "h-0.25rem",
  ".h-1.5": "h-0.375rem",
  ".h-2": "h-0.5rem",
  ".h-2.5": "h-0.625rem",
  ".h-3": "h-0.75rem",
  ".h-3.5": "h-0.875rem",
  ".h-4": "h-1rem",
  ".h-5": "h-1.25rem",
  ".h-6": "h-1.5rem",
  ".h-7": "h-1.75rem",
  ".h-8": "h-2rem",
  ".h-9": "h-2.25rem",
  ".h-10": "h-2.5rem",
  ".h-11": "h-2.75rem",
  ".h-12": "h-3rem",
  ".h-14": "h-3.5rem",
  ".h-16": "h-4rem",
  ".h-20": "h-5rem",
  ".h-24": "h-6rem",
  ".h-28": "h-7rem",
  ".h-32": "h-8rem",
  ".h-36": "h-9rem",
  ".h-40": "h-10rem",
  ".h-44": "h-11rem",
  ".h-48": "h-12rem",
  ".h-52": "h-13rem",
  ".h-56": "h-14rem",
  ".h-60": "h-15rem",
  ".h-64": "h-16rem",
  ".h-72": "h-18rem",
  ".h-80": "h-20rem",
  ".h-96": "h-24rem",
  ".h-auto": "h-auto",
  ".h-1/2": "h-50%",
  ".h-1/3": "h-33.333333%",
  ".h-2/3": "h-66.666667%",
  ".h-1/4": "h-25%",
  ".h-2/4": "h-50%",
  ".h-3/4": "h-75%",
  ".h-1/5": "h-20%",
  ".h-2/5": "h-40%",
  ".h-3/5": "h-60%",
  ".h-4/5": "h-80%",
  ".h-1/6": "h-16.666667%",
  ".h-2/6": "h-33.333333%",
  ".h-3/6": "h-50%",
  ".h-4/6": "h-66.666667%",
  ".h-5/6": "h-83.333333%",
  ".h-full": "h-100%",
  ".h-screen": "h-100vh",
  ".h-svh": "h-100svh",
  ".h-lvh": "h-100lvh",
  ".h-dvh": "h-100dvh",
  ".h-min": "h-[tx__min-content]",
  ".h-max": "h-[tx__max-content]",
  ".h-fit": "h-[tx__fit-content]",
  // min heigth

  ".min-h-0": "h-mn-0px",
  ".min-h-1": "h-mn-0.25rem",
  ".min-h-2": "h-mn-0.5rem",
  ".min-h-3": "h-mn-0.75rem",
  ".min-h-4": "h-mn-1rem",
  ".min-h-5": "h-mn-1.25rem",
  ".min-h-6": "h-mn-1.5rem",
  ".min-h-7": "h-mn-1.75rem",
  ".min-h-8": "h-mn-2rem",
  ".min-h-9": "h-mn-2.25rem",
  ".min-h-10": "h-mn-2.5rem",
  ".min-h-11": "h-mn-2.75rem",
  ".min-h-12": "h-mn-3rem",
  ".min-h-14": "h-mn-3.5rem",
  ".min-h-16": "h-mn-4rem",
  ".min-h-20": "h-mn-5rem",
  ".min-h-24": "h-mn-6rem",
  ".min-h-28": "h-mn-7rem",
  ".min-h-32": "h-mn-8rem",
  ".min-h-36": "h-mn-9rem",
  ".min-h-40": "h-mn-10rem",
  ".min-h-44": "h-mn-11rem",
  ".min-h-48": "h-mn-12rem",
  ".min-h-52": "h-mn-13rem",
  ".min-h-56": "h-mn-14rem",
  ".min-h-60": "h-mn-15rem",
  ".min-h-64": "h-mn-16rem",
  ".min-h-72": "h-mn-18rem",
  ".min-h-80": "h-mn-20rem",
  ".min-h-96": "h-mn-24rem",
  ".min-h-px": "h-mn-1px",
  ".min-h-0.5": "h-mn-0.125rem",
  ".min-h-1.5": "h-mn-0.375rem",
  ".min-h-2.5": "h-mn-0.625rem",
  ".min-h-3.5": "h-mn-0.875rem",
  ".min-h-full": "h-mn-100%",
  ".min-h-screen": "h-mn-100vh",
  ".min-h-svh": "h-mn-100svh",
  ".min-h-lvh": "h-mn-100lvh",
  ".min-h-dvh": "h-mn-100dvh",
  ".min-h-min": "h-mn-[tx__min-content]",
  ".min-h-max": "h-mn-[tx__max-content]",
  ".min-h-fit": "h-mn-[tx__fit-content]",
  // max height

  ".max-h-0": "w-mx-0px",
  ".max-h-px": "w-mx-1px",
  ".max-h-0.5": "w-mx-0.125rem",
  ".max-h-1": "w-mx-0.25rem",
  ".max-h-1.5": "w-mx-0.375rem",
  ".max-h-2": "w-mx-0.5rem",
  ".max-h-2.5": "w-mx-0.625rem",
  ".max-h-3": "w-mx-0.75rem",
  ".max-h-3.5": "w-mx-0.875rem",
  ".max-h-4": "w-mx-1rem",
  ".max-h-5": "w-mx-1.25rem",
  ".max-h-6": "w-mx-1.5rem",
  ".max-h-7": "w-mx-1.75rem",
  ".max-h-8": "w-mx-2rem",
  ".max-h-9": "w-mx-2.25rem",
  ".max-h-10": "w-mx-2.5rem",
  ".max-h-11": "w-mx-2.75rem",
  ".max-h-12": "w-mx-3rem",
  ".max-h-14": "w-mx-3.5rem",
  ".max-h-16": "w-mx-4rem",
  ".max-h-20": "w-mx-5rem",
  ".max-h-24": "w-mx-6rem",
  ".max-h-28": "w-mx-7rem",
  ".max-h-32": "w-mx-8rem",
  ".max-h-36": "w-mx-9rem",
  ".max-h-40": "w-mx-10rem",
  ".max-h-44": "w-mx-11rem",
  ".max-h-48": "w-mx-12rem",
  ".max-h-52": "w-mx-13rem",
  ".max-h-56": "w-mx-14rem",
  ".max-h-60": "w-mx-15rem",
  ".max-h-64": "w-mx-16rem",
  ".max-h-72": "w-mx-18rem",
  ".max-h-80": "w-mx-20rem",
  ".max-h-96": "w-mx-24rem",
  ".max-h-none": "w-mx-none",
  ".max-h-full": "w-mx-100%",
  ".max-h-screen": "w-mx-100vh",
  ".max-h-svh": "w-mx-100svh",
  ".max-h-lvh": "w-mx-100lvh",
  ".max-h-dvh": "w-mx-100dvh",
  ".max-h-min": "w-mx-[tx__min-content]",
  ".max-h-max": "w-mx-[tx__max-content]",
  ".max-h-fit": "w-mx-[tx__fit-content]",
  // size
  ".size-0": "box-0px",
  ".size-px": "box-1px",
  ".size-0.5": "box-0.125rem",
  ".size-1": "box-0.25rem",
  ".size-1.5": "box-0.375rem",
  ".size-2": "box-0.5rem",
  ".size-2.5": "box-0.625rem",
  ".size-3": "box-0.75rem",
  ".size-3.5": "box-0.875rem",
  ".size-4": "box-1rem",
  ".size-5": "box-1.25rem",
  ".size-6": "box-1.5rem",
  ".size-7": "box-1.75rem",
  ".size-8": "box-2rem",
  ".size-9": "box-2.25rem",
  ".size-10": "box-2.5rem",
  ".size-11": "box-2.75rem",
  ".size-12": "box-3rem",
  ".size-14": "box-3.5rem",
  ".size-16": "box-4rem",
  ".size-20": "box-5rem",
  ".size-24": "box-6rem",
  ".size-28": "box-7rem",
  ".size-32": "box-8rem",
  ".size-36": "box-9rem",
  ".size-40": "box-10rem",
  ".size-44": "box-11rem",
  ".size-48": "box-12rem",
  ".size-52": "box-13rem",
  ".size-56": "box-14rem",
  ".size-60": "box-15rem",
  ".size-64": "box-16rem",
  ".size-72": "box-18rem",
  ".size-80": "box-20rem",
  ".size-96": "box-24rem",
  ".size-auto": "box-auto",
  ".size-1/2": "box-50%",
  ".size-1/3": "box-33.333333%",
  ".size-2/3": "box-66.666667%",
  ".size-1/4": "box-25%",
  ".size-2/4": "box-50%",
  ".size-3/4": "box-75%",
  ".size-1/5": "box-20%",
  ".size-2/5": "box-40%",
  ".size-3/5": "box-60%",
  ".size-4/5": "box-80%",
  ".size-1/6": "box-16.666667%",
  ".size-2/6": "box-33.333333%",
  ".size-3/6": "box-50%",
  ".size-4/6": "box-66.666667%",
  ".size-5/6": "box-83.333333%",
  ".size-1/12": "box-8.333333%",
  ".size-2/12": "box-16.666667%",
  ".size-3/12": "box-25%",
  ".size-4/12": "box-33.333333%",
  ".size-5/12": "box-41.666667%",
  ".size-6/12": "box-50%",
  ".size-7/12": "box-58.333333%",
  ".size-8/12": "box-66.666667%",
  ".size-9/12": "box-75%",
  ".size-10/12": "box-83.333333%",
  ".size-11/12": "box-91.666667%",
  ".size-full": "box-100%",
  ".size-min": "box-[tx__min-content]",
  ".size-max": "box-[tx__max-content]",
  ".size-fit": "box-[tx__fit-content]",
  // family
  ".font-sans": "family-[font-sans]",
  ".font-serif": "family-[font-serif]",
  ".font-mono": "family-[font-mono]",
  // font size
  ".text-xs": "fs-0.75rem lh-1rem",
  ".text-sm": "fs-0.875rem lh-1.25rem",
  ".text-base": "fs-1rem lh-1.5rem",
  ".text-lg": "fs-1.125rem lh-1.75rem",
  ".text-xl": "fs-1.25rem lh-1.75rem",
  ".text-2xl": "fs-1.5rem lh-2rem",
  ".text-3xl": "fs-1.875rem lh-2.25rem",
  ".text-4xl": "fs-2.25rem lh-2.5rem",
  ".text-5xl": "fs-3rem lh-1",
  ".text-6xl": "fs-3.75rem lh-1",
  ".text-7xl": "fs-4.5rem lh-1",
  ".text-8xl": "fs-6rem lh-1",
  ".text-9xl": "fs-8rem lh-1",
  // font smoothing
  ".antialiased": "web-fs-antialiased moz-fs-grayscale",
  ".subpixel-antialiased": "web-fs-auto moz-fs-auto",
  // font style
  ".italic": "font-s-italic",
  ".not-italic": "font-s-normal",
  // font weight
  ".font-thin": "fw-100",
  ".font-extralight": "fw-200",
  ".font-light": "fw-300",
  ".font-normal": "fw-400",
  ".font-medium": "fw-500",
  ".font-semibold": "fw-600",
  ".font-bold": "fw-700",
  ".font-extrabold": "fw-800",
  ".font-black": "fw-900",
  // font variant numeric
  ".normal-nums": "font-v-num-normal",
  ".ordinal": "font-v-num-ordinal",
  ".slashed-zero": "font-v-num-[tx__slashed-zero]",
  ".lining-nums": "font-v-num-[tx__lining-nums]",
  ".oldstyle-nums": "font-v-num-[tx__oldstyle-nums]",
  ".proportional-nums": "font-v-num-[tx__proportional-nums]",
  ".tabular-nums": "font-v-num-[tx__tabular-nums]",
  ".diagonal-fractions": "font-v-num-[tx__diagonal-fractions]",
  ".stacked-fractions": "font-v-num-[tx__stacked-fractions]",
  // line spacing
  ".tracking-tighter": "ls--0.05em",
  ".tracking-tight": "ls--0.025em",
  ".tracking-normal": "ls-0em",
  ".tracking-wide": "ls-0.025em",
  ".tracking-wider": "ls-0.05em",
  ".tracking-widest": "ls-0.1em",
  // line clamp
  ".line-clamp-4":
    "over-hidden d-[tx__webkit-box] web-bx-o-vertical web-li-c-4",
  ".line-clamp-5":
    "over-hidden d-[tx__webkit-box] web-bx-o-vertical web-li-c-5",
  ".line-clamp-6":
    "over-hidden d-[tx__webkit-box] web-bx-o-vertical web-li-c-6",
  ".line-clamp-none": "over-visible d-block web-bx-o-horizontal web-li-c-none",
  // line height
  ".leading-3": "lh-0.75rem",
  ".leading-4": "lh-1rem",
  ".leading-5": "lh-1.25rem",
  ".leading-6": "lh-1.5rem",
  ".leading-7": "lh-1.75rem",
  ".leading-8": "lh-2rem",
  ".leading-9": "lh-2.25rem",
  ".leading-10": "lh-2.5rem",
  ".leading-none": "lh-1",
  ".leading-tight": "lh-1.25",
  ".leading-snug": "lh-1.375",
  ".leading-normal": "lh-1.5",
  ".leading-relaxed": "lh-1.625",
  ".leading-loose": "lh-2",
  // list style image
  ".list-image-none": "li-s-img-none",
  // list style position
  ".list-inside": "li-s-loc-inside",
  ".list-outside": "li-s-loc-outside",
  // list style type
  ".list-none": "li-s-type-none",
  ".list-disc": "li-s-type-disc",
  ".list-decimal": "li-s-type-decimal",
  // text align
  ".text-left": "ta-left",
  ".text-center": "ta-center",
  ".text-right": "ta-right",
  ".text-justify": "ta-justify",
  ".text-start": "ta-start",
  ".text-end": "ta-end",
  // color
  // Text decoration
  ".underline": "td-li-underline",
  ".overline": "td-li-overline",
  ".line-through": "td-li-line-through",
  ".no-underline": "td-li-none",
  // text decoration color
  // text decoration style
  ".decoration-solid": "td-s-solid",
  ".decoration-double": "td-s-double",
  ".decoration-dotted": "td-s-dotted",
  ".decoration-dashed": "td-s-dashed",
  ".decoration-wavy": "td-s-wavy",
  // text decoration thickness
  ".ecoration-auto": "td-t-auto",
  ".decoration-from-font": "td-t-[tx__from-font]",
  ".decoration-0": "td-t-0px",
  ".decoration-1": "td-t-1px",
  ".decoration-2": "td-t-2px",
  ".decoration-4": "td-t-4px",
  ".decoration-8": "td-t-8px",
  // text decoration offset
  ".underline-offset-auto": "td-o-auto",
  ".underline-offset-0": "td-o-0px",
  ".underline-offset-1": "td-o-1px",
  ".underline-offset-2": "td-o-2px",
  ".underline-offset-4": "td-o-4px",
  ".underline-offset-8": "td-o-8px",
  // text transform
  ".uppercase": "tn-uppercase",
  ".lowercase": "tn-lowercase",
  ".capitalize": "tn-capitalize",
  ".normal-case": "tn-none",
  // text overflow
  ".truncate": "over-hidden  text-over-ellipsis white-space: nowrap",
  ".text-ellipsis": "text-over-ellipsis",
  ".text-clip": "text-over-clip",
  // text wrap
  ".text-wrap": "text-wrap-wrap",
  ".text-nowrap": "text-wrap-nowrap",
  ".text-balance": "text-wrap-balance",
  ".text-pretty": "text-wrap-pretty",
  // text indent
  ".indent-0": "ti-0px",
  ".indent-px": "ti-1px",
  ".indent-0.5": "ti-0.125rem",
  ".indent-1": "ti-0.25rem",
  ".indent-1.5": "ti-0.375rem",
  ".indent-2": "ti-0.5rem",
  ".indent-2.5": "ti-0.625rem",
  ".indent-3": "ti-0.75rem",
  ".indent-3.5": "ti-0.875rem",
  ".indent-4": "ti-1rem",
  ".indent-5": "ti-1.25rem",
  ".indent-6": "ti-1.5rem",
  ".indent-7": "ti-1.75rem",
  ".indent-8": "ti-2rem",
  ".indent-9": "ti-2.25rem",
  ".indent-10": "ti-2.5rem",
  ".indent-11": "ti-2.75rem",
  ".indent-12": "ti-3rem",
  ".indent-14": "ti-3.5rem",
  ".indent-16": "ti-4rem",
  ".indent-20": "ti-5rem",
  ".indent-24": "ti-6rem",
  ".indent-28": "ti-7rem",
  ".indent-32": "ti-8rem",
  ".indent-36": "ti-9rem",
  ".indent-40": "ti-10rem",
  ".indent-44": "ti-11rem",
  ".indent-48": "ti-12rem",
  ".indent-52": "ti-13rem",
  ".indent-56": "ti-14rem",
  ".indent-60": "ti-15rem",
  ".indent-64": "ti-16rem",
  ".indent-72": "ti-18rem",
  ".indent-80": "ti-20rem",
  ".indent-96": "ti-24rem",
  // vertical align
  ".align-baseline": "v-align-baseline",
  ".align-top": "v-align-top",
  ".align-middle": "v-align-middle",
  ".align-bottom": "v-align-bottom",
  ".align-text-top": "v-align-[tx__text-top]",
  ".align-text-bottom": "v-align-[tx__text-bottom]",
  ".align-sub": "v-align-sub",
  ".align-super": "v-align-super",
  // white space
  ".whitespace-normal": "white-space-normal",
  ".whitespace-nowrap": "white-space-nowrap",
  ".whitespace-pre": "white-space-pre",
  ".whitespace-pre-line": "white-space-[tx__pre-line]",
  ".whitespace-pre-wrap": "white-space-[tx__pre-wrap]",
  ".whitespace-break-spaces": "white-space-[tx__break-spaces]",
  // word break
  ".break-normal": "over-wrap-normal w-brk-normal",
  ".break-words": "over-wrap-[tx__break-word]",
  ".break-all": "w-brk-[tx__break-all]",
  ".break-keep": "w-brk-[tx__keep-all]",
  // hyphens
  ".hyphens-none": "hyph-none",
  ".hyphens-manual": "hyph-manual",
  ".hyphens-auto": "hyph-auto",
  // content
  ".content-none": "content-none",
  // background attachment
  ".bg-fixed": "bg-attach-fixed",
  ".bg-local": "bg-attach-local",
  ".bg-scroll": "bg-attach-scroll",
  // background clip
  ".bg-clip-border": "bg-clip-[tx__border-box]",
  ".bg-clip-padding": "bg-clip-[tx__padding-box]",
  ".bg-clip-content": "bg-clip-[tx__content-box]",
  ".bg-clip-text": "bg-clip-text",
  // background origin
  ".bg-origin-border": "bg-origin-[tx__border-box]",
  ".bg-origin-padding": "bg-origin-[tx__padding-box]",
  ".bg-origin-content": "bg-origin-[tx__content-box]",
  // background position
  ".bg-bottom": "bg-loc-bottom",
  ".bg-center": "bg-loc-center",
  ".bg-left": "bg-loc-left",
  ".bg-left-bottom": "bg-loc-[tx__left-bottom]",
  ".bg-left-top": "bg-loc-[tx__left-top]",
  ".bg-right": "bg-loc-right",
  ".bg-right-bottom": "bg-loc-[tx__right-bottom]",
  ".bg-right-top": "bg-loc-[tx__right-top]",
  ".bg-top": "bg-loc-top",
  // background repeat
  ".bg-repeat": "bg-repeat-repeat",
  ".bg-no-repeat": "bg-repeat-[tx__no-repeat]",
  ".bg-repeat-x": "bg-repeat-[tx__repeat-x]",
  ".bg-repeat-y": "bg-repeat-[tx__repeat-y]",
  ".bg-repeat-round": "bg-repeat-round",
  ".bg-repeat-space": "bg-repeat-space",
  // background soze
  ".bg-auto": "bg-size-auto",
  ".bg-cover": "bg-size-cover",
  ".bg-contain": "bg-size-contain",
  // border-radius

  ".rounded-none": "br-0px",
  ".rounded-sm": "br-0.125rem",
  ".rounded": "br-0.25rem",
  ".rounded-md": "br-0.375rem",
  ".rounded-lg": "br-0.5rem",
  ".rounded-xl": "br-0.75rem",
  ".rounded-2xl": "br-1rem",
  ".rounded-3xl": "br-1.5rem",
  ".rounded-full": "br-9999px",
  ".rounded-s-none": "bdr-ss-radius-0px bdr-es-radius-0px",
  ".rounded-s-sm": "bdr-ss-radius-0.125rem bdr-es-radius-0.125rem",
  ".rounded-s": "bdr-ss-radius-0.25rem bdr-es-radius-0.25rem",
  ".rounded-s-md": "bdr-ss-radius-0.375rem bdr-es-radius-0.375rem",
  ".rounded-s-lg": "bdr-ss-radius-0.5rem bdr-es-radius-0.5rem",
  ".rounded-s-xl": "bdr-ss-radius-0.75rem bdr-es-radius-0.75rem",
  ".rounded-s-2xl": "bdr-ss-radius-1rem bdr-es-radius-1rem",
  ".rounded-s-3xl": "bdr-ss-radius-1.5rem bdr-es-radius-1.5rem",
  ".rounded-s-full": "bdr-ss-radius-9999px bdr-es-radius-9999px",
  ".rounded-e-none": "bdr-se-radius-0px bdr-ee-radius-0px",
  ".rounded-e-sm": "bdr-se-radius-0.125rem bdr-ee-radius-0.125rem",
  ".rounded-e": "bdr-se-radius-0.25rem bdr-ee-radius-0.25rem",
  ".rounded-e-md": "bdr-se-radius-0.375rem bdr-ee-radius-0.375rem",
  ".rounded-e-lg": "bdr-se-radius-0.5rem bdr-ee-radius-0.5rem",
  ".rounded-e-xl": "bdr-se-radius-0.75rem bdr-ee-radius-0.75rem",
  ".rounded-e-2xl": "bdr-se-radius-1rem bdr-ee-radius-1rem",
  ".rounded-e-3xl": "bdr-se-radius-1.5rem bdr-ee-radius-1.5rem",
  ".rounded-e-full": "bdr-se-radius-9999px bdr-ee-radius-9999px",
  ".rounded-t-none": "radius-tl-0px radius-tr-0px",
  ".rounded-t-sm": "radius-tl-0.125rem radius-tr-0.125rem",
  ".rounded-t": "radius-tl-0.25rem radius-tr-0.25rem",
  ".rounded-t-md": "radius-tl-0.375rem radius-tr-0.375rem",
  ".rounded-t-lg": "radius-tl-0.5rem radius-tr-0.5rem",
  ".rounded-t-xl": "radius-tl-0.75rem radius-tr-0.75rem",
  ".rounded-t-2xl": "radius-tl-1rem radius-tr-1rem",
  ".rounded-t-3xl": "radius-tl-1.5rem radius-tr-1.5rem",
  ".rounded-t-full": "radius-tl-9999px radius-tr-9999px",
  ".rounded-r-none": "radius-tr-0px radius-br-0px",
  ".rounded-r-sm": "radius-tr-0.125rem radius-br-0.125rem",
  ".rounded-r": "radius-tr-0.25rem radius-br-0.25rem",
  ".rounded-r-md": "radius-tr-0.375rem radius-br-0.375rem",
  ".rounded-r-lg": "radius-tr-0.5rem radius-br-0.5rem",
  ".rounded-r-xl": "radius-tr-0.75rem radius-br-0.75rem",
  ".rounded-r-2xl": "radius-tr-1rem radius-br-1rem",
  ".rounded-r-3xl": "radius-tr-1.5rem radius-br-1.5rem",
  ".rounded-r-full": "radius-tr-9999px radius-br-9999px",
  ".rounded-b-none": "radius-br-0px radius-bl-0px",
  ".rounded-b-sm": "radius-br-0.125rem radius-bl-0.125rem",
  ".rounded-b": "radius-br-0.25rem radius-bl-0.25rem",
  ".rounded-b-md": "radius-br-0.375rem radius-bl-0.375rem",
  ".rounded-b-lg": "radius-br-0.5rem radius-bl-0.5rem",
  ".rounded-b-xl": "radius-br-0.75rem radius-bl-0.75rem",
  ".rounded-b-2xl": "radius-br-1rem radius-bl-1rem",
  ".rounded-b-3xl": "radius-br-1.5rem radius-bl-1.5rem",
  ".rounded-b-full": "radius-br-9999px radius-bl-9999px",
  ".rounded-l-none": "radius-tl-0px radius-bl-0px",
  ".rounded-l-sm": "radius-tl-0.125rem radius-bl-0.125rem",
  ".rounded-l": "radius-tl-0.25rem radius-bl-0.25rem",
  ".rounded-l-md": "radius-tl-0.375rem radius-bl-0.375rem",
  ".rounded-l-lg": "radius-tl-0.5rem radius-bl-0.5rem",
  ".rounded-l-xl": "radius-tl-0.75rem radius-bl-0.75rem",
  ".rounded-l-2xl": "radius-tl-1rem radius-bl-1rem",
  ".rounded-l-3xl": "radius-tl-1.5rem radius-bl-1.5rem",
  ".rounded-l-full": "radius-tl-9999px radius-bl-9999px",
  ".rounded-ss-none": "bdr-ss-radius-0px",
  ".rounded-ss-sm": "bdr-ss-radius-0.125rem",
  ".rounded-ss": "bdr-ss-radius-0.25rem",
  ".rounded-ss-md": "bdr-ss-radius-0.375rem",
  ".rounded-ss-lg": "bdr-ss-radius-0.5rem",
  ".rounded-ss-xl": "bdr-ss-radius-0.75rem",
  ".rounded-ss-2xl": "bdr-ss-radius-1rem",
  ".rounded-ss-3xl": "bdr-ss-radius-1.5rem",
  ".rounded-ss-full": "bdr-ss-radius-9999px",
  ".rounded-se-none": "bdr-se-radius-0px",
  ".rounded-se-sm": "bdr-se-radius-0.125rem",
  ".rounded-se": "bdr-se-radius-0.25rem",
  ".rounded-se-md": "bdr-se-radius-0.375rem",
  ".rounded-se-lg": "bdr-se-radius-0.5rem",
  ".rounded-se-xl": "bdr-se-radius-0.75rem",
  ".rounded-se-2xl": "bdr-se-radius-1rem",
  ".rounded-se-3xl": "bdr-se-radius-1.5rem",
  ".rounded-se-full": "bdr-se-radius-9999px",
  ".rounded-ee-none": "bdr-ee-radius-0px",
  ".rounded-ee-sm": "bdr-ee-radius-0.125rem",
  ".rounded-ee": "bdr-ee-radius-0.25rem",
  ".rounded-ee-md": "bdr-ee-radius-0.375rem",
  ".rounded-ee-lg": "bdr-ee-radius-0.5rem",
  ".rounded-ee-xl": "bdr-ee-radius-0.75rem",
  ".rounded-ee-2xl": "bdr-ee-radius-1rem",
  ".rounded-ee-3xl": "bdr-ee-radius-1.5rem",
  ".rounded-ee-full": "bdr-ee-radius-9999px",
  ".rounded-es-none": "bdr-es-radius-0px",
  ".rounded-es-sm": "bdr-es-radius-0.125rem",
  ".rounded-es": "bdr-es-radius-0.25rem",
  ".rounded-es-md": "bdr-es-radius-0.375rem",
  ".rounded-es-lg": "bdr-es-radius-0.5rem",
  ".rounded-es-xl": "bdr-es-radius-0.75rem",
  ".rounded-es-2xl": "bdr-es-radius-1rem",
  ".rounded-es-3xl": "bdr-es-radius-1.5rem",
  ".rounded-es-full": "bdr-es-radius-9999px",
  ".rounded-tl-none": "radius-tl-0px",
  ".rounded-tl-sm": "radius-tl-0.125rem",
  ".rounded-tl": "radius-tl-0.25rem",
  ".rounded-tl-md": "radius-tl-0.375rem",
  ".rounded-tl-lg": "radius-tl-0.5rem",
  ".rounded-tl-xl": "radius-tl-0.75rem",
  ".rounded-tl-2xl": "radius-tl-1rem",
  ".rounded-tl-3xl": "radius-tl-1.5rem",
  ".rounded-tl-full": "radius-tl-9999px",
  ".rounded-tr-none": "radius-tr-0px",
  ".rounded-tr-sm": "radius-tr-0.125rem",
  ".rounded-tr": "radius-tr-0.25rem",
  ".rounded-tr-md": "radius-tr-0.375rem",
  ".rounded-tr-lg": "radius-tr-0.5rem",
  ".rounded-tr-xl": "radius-tr-0.75rem",
  ".rounded-tr-2xl": "radius-tr-1rem",
  ".rounded-tr-3xl": "radius-tr-1.5rem",
  ".rounded-tr-full": "radius-tr-9999px",
  ".rounded-br-none": "radius-br-0px",
  ".rounded-br-sm": "radius-br-0.125rem",
  ".rounded-br": "radius-br-0.25rem",
  ".rounded-br-md": "radius-br-0.375rem",
  ".rounded-br-lg": "radius-br-0.5rem",
  ".rounded-br-xl": "radius-br-0.75rem",
  ".rounded-br-2xl": "radius-br-1rem",
  ".rounded-br-3xl": "radius-br-1.5rem",
  ".rounded-br-full": "radius-br-9999px",
  ".rounded-bl-none": "radius-bl-0px",
  ".rounded-bl-sm": "radius-bl-0.125rem",
  ".rounded-bl": "radius-bl-0.25rem",
  ".rounded-bl-md": "radius-bl-0.375rem",
  ".rounded-bl-lg": "radius-bl-0.5rem",
  ".rounded-bl-xl": "radius-bl-0.75rem",
  ".rounded-bl-2xl": "radius-bl-1rem",
  ".rounded-bl-3xl": "radius-bl-1.5rem",
  ".rounded-bl-full": "radius-bl-9999px",
  // border width

  ".border-0": "bw-0px",
  ".border-2": "bw-2px",
  ".border-4": "bw-4px",
  ".border-8": "bw-8px",
  ".border": "bw-1px",
  ".border-x-0": "bw-left-0px bw-right-0px",
  ".border-x-2": "bw-left-2px bw-right-2px",
  ".border-x-4": "bw-left-4px bw-right-4px",
  ".border-x-8": "bw-left-8px bw-right-8px",
  ".border-x": "bw-left-1px bw-right-1px",
  ".border-y-0": "bw-top-0px bw-bottom-0px",
  ".border-y-2": "bw-top-2px bw-bottom-2px",
  ".border-y-4": "bw-top-4px bw-bottom-4px",
  ".border-y-8": "bw-top-8px bw-bottom-8px",
  ".border-y": "bw-top-1px bw-bottom-1px",
  ".border-s-0": "bdr-is-width-0px",
  ".border-s-2": "bdr-is-width-2px",
  ".border-s-4": "bdr-is-width-4px",
  ".border-s-8": "bdr-is-width-8px",
  ".border-s": "bdr-is-width-1px",
  ".border-e-0": "bdr-ie-width-0px",
  ".border-e-2": "bdr-ie-width-2px",
  ".border-e-4": "bdr-ie-width-4px",
  ".border-e-8": "bdr-ie-width-8px",
  ".border-e": "bdr-ie-width-1px",
  ".border-t-0": "bw-top-0px",
  ".border-t-2": "bw-top-2px",
  ".border-t-4": "bw-top-4px",
  ".border-t-8": "bw-top-8px",
  ".border-t": "bw-top-1px",
  ".border-r-0": "bw-right-0px",
  ".border-r-2": "bw-right-2px",
  ".border-r-4": "bw-right-4px",
  ".border-r-8": "bw-right-8px",
  ".border-r": "bw-right-1p",
  ".border-b-0": "bw-bottom-0px",
  ".border-b-2": "bw-bottom-2px",
  ".border-b-4": "bw-bottom-4px",
  ".border-b-8": "bw-bottom-8px",
  ".border-b": "bw-bottom-1px",
  ".border-l-0": "bw-left-0px",
  ".border-l-2": "bw-left-2px",
  ".border-l-4": "bw-left-4px",
  ".border-l-8": "bw-left-8px",
  ".border-l": "bw-left-1px",
  // border style
  ".border-solid": "bs-solid",
  ".border-dashed": "bs-dashed",
  ".border-dotted": "bs-dotted",
  ".border-double": "bs-double",
  ".border-hidden": "bs-hidden",
  ".border-none": "bs-none",
  // divide
  ".divide-x-0 > * + *": "bw-right-0px bw-left-0px",
  ".divide-x-2 > * + *": "bw-right-0px bw-left-2px",
  ".divide-x-4 > * + *": "bw-right-0px bw-left-4px",
  ".divide-x-8 > * + *": "bw-right-0px bw-left-8px",
  ".divide-x > * + *": "bw-right-0px bw-left-1px",
  ".divide-y-0 > * + *": "bw-top-0px bw-bottom-0px",
  ".divide-y-2 > * + *": "bw-top-2px bw-bottom-0px",
  ".divide-y-4 > * + *": "bw-top-4px bw-bottom-0px",
  ".divide-y-8 > * + *": "bw-top-8px bw-bottom-0px",
  ".divide-y > * + *": "bw-top-1px bw-bottom-0px",
  // divide color
  // divide style
  ".divide-solid > * + *": "bs-solid",
  ".divide-dashed > * + *": "bs-dashed",
  ".divide-dotted > * + *": "bs-dotted",
  ".divide-double > * + *": "bs-double",
  ".divide-none > * + *": "bs-none",
  // outline width
  ".outline-0": "ol-w-0px",
  ".outline-1": "ol-w-1px",
  ".outline-2": "ol-w-2px",
  ".outline-4": "ol-w-4px",
  ".outline-8": "ol-w-8px",
  // outline color
  // outline style
  ".outline-none": "ol-w-2px ol-s-solid ol-c-transparent ol-o-2px",
  ".outline": "ol-s-solid",
  ".outline-dashed": "ol-s-dashed",
  ".outline-dotted": "ol-s-dotted",
  ".outline-double": "ol-s-double",
  // outline offset
  ".outline-offset-0": "ol-o-0px",
  ".outline-offset-1": "ol-o-1px",
  ".outline-offset-2": "ol-o-2px",
  ".outline-offset-4": "ol-o-4px",
  ".outline-offset-8": "ol-o-8px",
  // box shadow
  ".shadow": "shadow-[shadow]",
  ".shadow-md": "shadow-[shadow-md]",
  ".shadow-lg": "shadow-[shadow-lg]",
  ".shadow-xl": "shadow-[shadow-xl]",
  ".shadow-2xl": "shadow-[shadow-2xl]",
  ".shadow-inner": "shadow-[shadow-inner]",
  ".shadow-none": "shadow-[shadow-none]",
  // opacity
  ".opacity-0": "opa-0",
  ".opacity-5": "opa-0.05",
  ".opacity-10": "opa-0.1",
  ".opacity-15": "opa-0.15",
  ".opacity-20": "opa-0.2",
  ".opacity-25": "opa-0.25",
  ".opacity-30": "opa-0.3",
  ".opacity-35": "opa-0.35",
  ".opacity-40": "opa-0.4",
  ".opacity-45": "opa-0.45",
  ".opacity-50": "opa-0.5",
  ".opacity-55": "opa-0.55",
  ".opacity-60": "opa-0.6",
  ".opacity-65": "opa-0.65",
  ".opacity-70": "opa-0.7",
  ".opacity-75": "opa-0.75",
  ".opacity-80": "opa-0.8",
  ".opacity-85": "opa-0.85",
  ".opacity-90": "opa-0.9",
  ".opacity-95": "opa-0.95",
  ".opacity-100": "opa-1",
  // mix blend mode
  ".mix-blend-normal": "blend-mode-normal",
  ".mix-blend-multiply": "blend-mode-multiply",
  ".mix-blend-screen": "blend-mode-screen",
  ".mix-blend-overlay": "blend-mode-overlay",
  ".mix-blend-darken": "blend-mode-darken",
  ".mix-blend-lighten": "blend-mode-lighten",
  ".mix-blend-color-dodge": "blend-mode-[tx__color-dodge]",
  ".mix-blend-color-burn": "blend-mode-[tx__color-burn]",
  ".mix-blend-hard-light": "blend-mode-[tx__hard-light]",
  ".mix-blend-soft-light": "blend-mode-[tx__soft-light]",
  ".mix-blend-difference": "blend-mode-difference",
  ".mix-blend-exclusion": "blend-mode-exclusion",
  ".mix-blend-hue": "blend-mode-hue",
  ".mix-blend-saturation": "blend-mode-saturation",
  ".mix-blend-color": "blend-mode-color",
  ".mix-blend-luminosity": "blend-mode-luminosity",
  ".mix-blend-plus-darker": "blend-mode-[tx__plus-darker]",
  ".mix-blend-plus-lighter": "blend-mode-[tx__plus-lighter]",
  // background blend mode
  ".bg-blend-normal": "bg-blend-normal",
  ".bg-blend-multiply": "bg-blend-multiply",
  ".bg-blend-screen": "bg-blend-screen",
  ".bg-blend-overlay": "bg-blend-overlay",
  ".bg-blend-darken": "bg-blend-darken",
  ".bg-blend-lighten": "bg-blend-lighten",
  ".bg-blend-color-dodge": "bg-blend-[tx__color-dodge]",
  ".bg-blend-color-burn": "bg-blend-[tx__color-burn]",
  ".bg-blend-hard-light": "bg-blend-[tx__hard-light]",
  ".bg-blend-soft-light": "bg-blend-[tx__soft-light]",
  ".bg-blend-difference": "bg-blend-difference",
  ".bg-blend-exclusion": "bg-blend-exclusion",
  ".bg-blend-hue": "bg-blend-hue",
  ".bg-blend-saturation": "bg-blend-saturation",
  ".bg-blend-color": "bg-blend-color",
  ".bg-blend-luminosity": "bg-blend-luminosity",
  // filter
  // border collapse
  ".border-collapse": "bd-colp-collapse",
  ".border-separate": "bd-colp-separate",
  // transition property
  ".transition-none": "tr-prop-none",
  ".transition-all": "tr-prop-all tr-timing-[tx__ease-in-out] tr-time-150ms",
  ".transition":
    "tr-prop-[tx__tr-prop] tr-timing-[tx__ease-in-out] tr-time-150ms",
  ".transition-colors":
    "tr-prop-[tx__tr-color] tr-timing-[tx__ease-in-out] tr-time-150ms",
  ".transition-opacity":
    "tr-prop-opacity tr-timing-[tx__ease-in-out] tr-time-150ms",
  ".transition-shadow":
    "tr-prop-[tx__bs] tr-timing-[tx__ease-in-out] tr-time-150ms",
  ".transition-transform":
    "tr-prop-transform tr-timing-[tx__ease-in-out] tr-time-150ms",
  // transition duration
  ".duration-0": "tr-time-0s",
  ".duration-75": "tr-time-75ms",
  ".duration-100": "tr-time-100ms",
  ".duration-150": "tr-time-150ms",
  ".duration-200": "tr-time-200ms",
  ".duration-300": "tr-time-300ms",
  ".duration-500": "tr-time-500ms",
  ".duration-700": "tr-time-700ms",
  ".duration-1000": "tr-time-1000ms",
  // transition timing function
  ".ease-linear": "tr-timing-linear",
  ".ease-in": "tr-timing-[tx__ease-in]",
  ".ease-out": "tr-timing-[tx__ease-out]",
  ".ease-in-out": "tr-timing-[tx__ease-in-out]",
  // transition delay
  ".delay-0": "tr-delay-0s",
  ".delay-75": "tr-delay-75ms",
  ".delay-100": "tr-delay-100ms",
  ".delay-150": "tr-delay-150ms",
  ".delay-200": "tr-delay-200ms",
  ".delay-300": "tr-delay-300ms",
  ".delay-500": "tr-delay-500ms",
  ".delay-700": "tr-delay-700ms",
  ".delay-1000": "tr-delay-1000ms",
};
